const ACCOUNTS_REQUEST = "ACCOUNTS_REQUEST";
const ACCOUNTS_ERROR = "ACCOUNTS_ERROR";
const ACCOUNTS_SUCCESS = "ACCOUNTS_SUCCESS";
const ACCOUNT_REQUEST = "ACCOUNT_REQUEST";
const ACCOUNT_ERROR = "ACCOUNT_ERROR";
const ACCOUNT_SUCCESS = "ACCOUNT_SUCCESS";
const ACCOUNT_ADD_REQUEST = "ACCOUNT_ADD_REQUEST";
const ACCOUNT_ADD_ERROR = "ACCOUNT_ADD_ERROR";
const ACCOUNT_ADD_SUCCESS = "ACCOUNT_ADD_SUCCESS";
const ACCOUNT_EDIT_REQUEST = "ACCOUNT_EDIT_REQUEST";
const ACCOUNT_EDIT_ERROR = "ACCOUNT_EDIT_ERROR";
const ACCOUNT_EDIT_SUCCESS = "ACCOUNT_EDIT_SUCCESS";
const ACCOUNT_DELETE_REQUEST = "ACCOUNT_DELETE_REQUEST";
const ACCOUNT_DELETE_ERROR = "ACCOUNT_DELETE_ERROR";
const ACCOUNT_DELETE_SUCCESS = "ACCOUNT_DELETE_SUCCESS";

const RESET_AFTER_REQUEST = "RESET_AFTER_REQUEST";

export default {
  ACCOUNTS_REQUEST,
  ACCOUNTS_ERROR,
  ACCOUNTS_SUCCESS,
  ACCOUNT_REQUEST,
  ACCOUNT_ERROR,
  ACCOUNT_SUCCESS,
  ACCOUNT_ADD_REQUEST,
  ACCOUNT_ADD_ERROR,
  ACCOUNT_ADD_SUCCESS,
  ACCOUNT_EDIT_REQUEST,
  ACCOUNT_EDIT_ERROR,
  ACCOUNT_EDIT_SUCCESS,
  ACCOUNT_DELETE_REQUEST,
  ACCOUNT_DELETE_ERROR,
  ACCOUNT_DELETE_SUCCESS,
  RESET_AFTER_REQUEST,
};