const REFERRALS_REQUEST = "REFERRALS_REQUEST";
const REFERRALS_ERROR = "REFERRALS_ERROR";
const REFERRALS_SUCCESS = "REFERRALS_SUCCESS";
const REFERRAL_REQUEST = "REFERRAL_REQUEST";
const REFERRAL_ERROR = "REFERRAL_ERROR";
const REFERRAL_SUCCESS = "REFERRAL_SUCCESS";
const REFERRAL_ADD_REQUEST = "REFERRAL_ADD_REQUEST";
const REFERRAL_ADD_ERROR = "REFERRAL_ADD_ERROR";
const REFERRAL_ADD_SUCCESS = "REFERRAL_ADD_SUCCESS";
const REFERRAL_EDIT_REQUEST = "REFERRAL_EDIT_REQUEST";
const REFERRAL_EDIT_ERROR = "REFERRAL_EDIT_ERROR";
const REFERRAL_EDIT_SUCCESS = "REFERRAL_EDIT_SUCCESS";
const REFERRAL_DELETE_REQUEST = "REFERRAL_DELETE_REQUEST";
const REFERRAL_DELETE_ERROR = "REFERRAL_DELETE_ERROR";
const REFERRAL_DELETE_SUCCESS = "REFERRAL_DELETE_SUCCESS";

const REFERRALS_USER_ACCOUNT_REQUEST = "REFERRALS_USER_ACCOUNT_REQUEST";
const REFERRALS_USER_ACCOUNT_ERROR = "REFERRALS_USER_ACCOUNT_ERROR";
const REFERRALS_USER_ACCOUNT_SUCCESS = "REFERRALS_USER_ACCOUNT_SUCCESS";

const RESET_AFTER_REQUEST = "RESET_AFTER_REQUEST";

export default {
  REFERRALS_REQUEST,
  REFERRALS_ERROR,
  REFERRALS_SUCCESS,
  REFERRAL_REQUEST,
  REFERRAL_ERROR,
  REFERRAL_SUCCESS,
  REFERRAL_ADD_REQUEST,
  REFERRAL_ADD_ERROR,
  REFERRAL_ADD_SUCCESS,
  REFERRAL_EDIT_REQUEST,
  REFERRAL_EDIT_ERROR,
  REFERRAL_EDIT_SUCCESS,
  REFERRAL_DELETE_REQUEST,
  REFERRAL_DELETE_ERROR,
  REFERRAL_DELETE_SUCCESS,
  REFERRALS_USER_ACCOUNT_REQUEST,
  REFERRALS_USER_ACCOUNT_ERROR,
  REFERRALS_USER_ACCOUNT_SUCCESS,
  RESET_AFTER_REQUEST,

};