const INVESTMENT_OPERATIONS_REQUEST = "INVESTMENT_OPERATIONS_REQUEST";
const INVESTMENT_OPERATIONS_ERROR = "INVESTMENT_OPERATIONS_ERROR";
const INVESTMENT_OPERATIONS_SUCCESS = "INVESTMENT_OPERATIONS_SUCCESS";
const INVESTMENT_OPERATION_ADD_REQUEST = "INVESTMENT_OPERATION_ADD_REQUEST";
const INVESTMENT_OPERATION_ADD_ERROR = "INVESTMENT_OPERATION_ADD_ERROR";
const INVESTMENT_OPERATION_ADD_SUCCESS = "INVESTMENT_OPERATION_ADD_SUCCESS";
const INVESTMENT_OPERATION_EDIT_REQUEST = "INVESTMENT_OPERATION_EDIT_REQUEST";
const INVESTMENT_OPERATION_EDIT_ERROR = "INVESTMENT_OPERATION_EDIT_ERROR";
const INVESTMENT_OPERATION_EDIT_SUCCESS = "INVESTMENT_OPERATION_EDIT_SUCCESS";
const INVESTMENT_OPERATION_DELETE_REQUEST = "INVESTMENT_OPERATION_DELETE_REQUEST";
const INVESTMENT_OPERATION_DELETE_ERROR = "INVESTMENT_OPERATION_DELETE_ERROR";
const INVESTMENT_OPERATION_DELETE_SUCCESS = "INVESTMENT_OPERATION_DELETE_SUCCESS";

const RESET_AFTER_REQUEST = "RESET_AFTER_REQUEST";

export default {
  INVESTMENT_OPERATIONS_REQUEST,
  INVESTMENT_OPERATIONS_ERROR,
  INVESTMENT_OPERATIONS_SUCCESS,
  INVESTMENT_OPERATION_ADD_REQUEST,
  INVESTMENT_OPERATION_ADD_ERROR,
  INVESTMENT_OPERATION_ADD_SUCCESS,
  INVESTMENT_OPERATION_EDIT_REQUEST,
  INVESTMENT_OPERATION_EDIT_ERROR,
  INVESTMENT_OPERATION_EDIT_SUCCESS,
  INVESTMENT_OPERATION_DELETE_REQUEST,
  INVESTMENT_OPERATION_DELETE_ERROR,
  INVESTMENT_OPERATION_DELETE_SUCCESS,
  RESET_AFTER_REQUEST,
};