const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
const PRODUCTS_ERROR = "PRODUCTS_ERROR";
const PRODUCTS_SUCCESS = "PRODUCTS_SUCCESS";
const PRODUCT_ADD_REQUEST = "PRODUCT_ADD_REQUEST";
const PRODUCT_ADD_ERROR = "PRODUCT_ADD_ERROR";
const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS";
const PRODUCT_EDIT_REQUEST = "PRODUCT_EDIT_REQUEST";
const PRODUCT_EDIT_ERROR = "PRODUCT_EDIT_ERROR";
const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";
const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
const PRODUCT_DELETE_ERROR = "PRODUCT_DELETE_ERROR";
const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";

const RESET_AFTER_REQUEST = "RESET_AFTER_REQUEST";

export default {
  PRODUCTS_REQUEST,
  PRODUCTS_ERROR,
  PRODUCTS_SUCCESS,
  PRODUCT_ADD_REQUEST,
  PRODUCT_ADD_ERROR,
  PRODUCT_ADD_SUCCESS,
  PRODUCT_EDIT_REQUEST,
  PRODUCT_EDIT_ERROR,
  PRODUCT_EDIT_SUCCESS,
  PRODUCT_DELETE_REQUEST,
  PRODUCT_DELETE_ERROR,
  PRODUCT_DELETE_SUCCESS,
  RESET_AFTER_REQUEST,
};