const INVESTMENT_MOVEMENTS_REQUEST = "INVESTMENT_MOVEMENTS_REQUEST";
const INVESTMENT_MOVEMENTS_ERROR = "INVESTMENT_MOVEMENTS_ERROR";
const INVESTMENT_MOVEMENTS_SUCCESS = "INVESTMENT_MOVEMENTS_SUCCESS";
const INVESTMENT_MOVEMENT_ADD_REQUEST = "INVESTMENT_MOVEMENT_ADD_REQUEST";
const INVESTMENT_MOVEMENT_ADD_ERROR = "INVESTMENT_MOVEMENT_ADD_ERROR";
const INVESTMENT_MOVEMENT_ADD_SUCCESS = "INVESTMENT_MOVEMENT_ADD_SUCCESS";
const INVESTMENT_MOVEMENT_EDIT_REQUEST = "INVESTMENT_MOVEMENT_EDIT_REQUEST";
const INVESTMENT_MOVEMENT_EDIT_ERROR = "INVESTMENT_MOVEMENT_EDIT_ERROR";
const INVESTMENT_MOVEMENT_EDIT_SUCCESS = "INVESTMENT_MOVEMENT_EDIT_SUCCESS";
const INVESTMENT_MOVEMENT_DELETE_REQUEST = "INVESTMENT_MOVEMENT_DELETE_REQUEST";
const INVESTMENT_MOVEMENT_DELETE_ERROR = "INVESTMENT_MOVEMENT_DELETE_ERROR";
const INVESTMENT_MOVEMENT_DELETE_SUCCESS = "INVESTMENT_MOVEMENT_DELETE_SUCCESS";

const RESET_AFTER_REQUEST = "RESET_AFTER_REQUEST";

export default {
  INVESTMENT_MOVEMENTS_REQUEST,
  INVESTMENT_MOVEMENTS_ERROR,
  INVESTMENT_MOVEMENTS_SUCCESS,
  INVESTMENT_MOVEMENT_ADD_REQUEST,
  INVESTMENT_MOVEMENT_ADD_ERROR,
  INVESTMENT_MOVEMENT_ADD_SUCCESS,
  INVESTMENT_MOVEMENT_EDIT_REQUEST,
  INVESTMENT_MOVEMENT_EDIT_ERROR,
  INVESTMENT_MOVEMENT_EDIT_SUCCESS,
  INVESTMENT_MOVEMENT_DELETE_REQUEST,
  INVESTMENT_MOVEMENT_DELETE_ERROR,
  INVESTMENT_MOVEMENT_DELETE_SUCCESS,
  RESET_AFTER_REQUEST,
};