const FUND_OPERATIONS_REQUEST = 'FUND_OPERATIONS_REQUEST'
const FUND_OPERATIONS_ERROR = 'FUND_OPERATIONS_ERROR'
const FUND_OPERATIONS_SUCCESS = 'FUND_OPERATIONS_SUCCESS'
const FUND_OPERATION_ADD_REQUEST = 'FUND_OPERATION_ADD_REQUEST'
const FUND_OPERATION_ADD_ERROR = 'FUND_OPERATION_ADD_ERROR'
const FUND_OPERATION_ADD_SUCCESS = 'FUND_OPERATION_ADD_SUCCESS'
const FUND_OPERATION_EDIT_REQUEST = 'FUND_OPERATION_EDIT_REQUEST'
const FUND_OPERATION_EDIT_ERROR = 'FUND_OPERATION_EDIT_ERROR'
const FUND_OPERATION_EDIT_SUCCESS = 'FUND_OPERATION_EDIT_SUCCESS'
const FUND_OPERATION_DELETE_REQUEST = 'FUND_OPERATION_DELETE_REQUEST'
const FUND_OPERATION_DELETE_ERROR = 'FUND_OPERATION_DELETE_ERROR'
const FUND_OPERATION_DELETE_SUCCESS = 'FUND_OPERATION_DELETE_SUCCESS'
const FUND_OPERATION_BULK_UPDATE_REQUEST = 'FUND_OPERATION_BULK_UPDATE_REQUEST'
const FUND_OPERATION_BULK_UPDATE_ERROR = 'FUND_OPERATION_BULK_UPDATE_ERROR'
const FUND_OPERATION_BULK_UPDATE_SUCCESS = 'FUND_OPERATION_BULK_UPDATE_SUCCESS'

const RESET_AFTER_REQUEST = 'RESET_AFTER_REQUEST'

export default {
  FUND_OPERATIONS_REQUEST,
  FUND_OPERATIONS_ERROR,
  FUND_OPERATIONS_SUCCESS,
  FUND_OPERATION_ADD_REQUEST,
  FUND_OPERATION_ADD_ERROR,
  FUND_OPERATION_ADD_SUCCESS,
  FUND_OPERATION_EDIT_REQUEST,
  FUND_OPERATION_EDIT_ERROR,
  FUND_OPERATION_EDIT_SUCCESS,
  FUND_OPERATION_DELETE_REQUEST,
  FUND_OPERATION_DELETE_ERROR,
  FUND_OPERATION_DELETE_SUCCESS,
  FUND_OPERATION_BULK_UPDATE_REQUEST,
  FUND_OPERATION_BULK_UPDATE_ERROR,
  FUND_OPERATION_BULK_UPDATE_SUCCESS,
  RESET_AFTER_REQUEST,
}
