const COMMODITIES_REQUEST = "COMMODITIES_REQUEST";
const COMMODITIES_ERROR = "COMMODITIES_ERROR";
const COMMODITIES_SUCCESS = "COMMODITIES_SUCCESS";
const COMMODITY_ADD_REQUEST = "COMMODITY_ADD_REQUEST";
const COMMODITY_ADD_ERROR = "COMMODITY_ADD_ERROR";
const COMMODITY_ADD_SUCCESS = "COMMODITY_ADD_SUCCESS";
const COMMODITY_EDIT_REQUEST = "COMMODITY_EDIT_REQUEST";
const COMMODITY_EDIT_ERROR = "COMMODITY_EDIT_ERROR";
const COMMODITY_EDIT_SUCCESS = "COMMODITY_EDIT_SUCCESS";
const COMMODITY_DELETE_REQUEST = "COMMODITY_DELETE_REQUEST";
const COMMODITY_DELETE_ERROR = "COMMODITY_DELETE_ERROR";
const COMMODITY_DELETE_SUCCESS = "COMMODITY_DELETE_SUCCESS";

const RESET_AFTER_REQUEST = "RESET_AFTER_REQUEST";

export default {
  COMMODITIES_REQUEST,
  COMMODITIES_ERROR,
  COMMODITIES_SUCCESS,
  COMMODITY_ADD_REQUEST,
  COMMODITY_ADD_ERROR,
  COMMODITY_ADD_SUCCESS,
  COMMODITY_EDIT_REQUEST,
  COMMODITY_EDIT_ERROR,
  COMMODITY_EDIT_SUCCESS,
  COMMODITY_DELETE_REQUEST,
  COMMODITY_DELETE_ERROR,
  COMMODITY_DELETE_SUCCESS,
  RESET_AFTER_REQUEST,
};