const USERS_REQUEST = "USERS_REQUEST";
const USERS_ERROR = "USERS_ERROR";
const USERS_SUCCESS = "USERS_SUCCESS";
const USER_ADD_REQUEST = "USER_ADD_REQUEST";
const USER_ADD_ERROR = "USER_ADD_ERROR";
const USER_ADD_SUCCESS = "USER_ADD_SUCCESS";
const USER_EDIT_REQUEST = "USER_EDIT_REQUEST";
const USER_EDIT_ERROR = "USER_EDIT_ERROR";
const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
const USER_DELETE_ERROR = "USER_DELETE_ERROR";
const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";

const RESET_AFTER_REQUEST = "RESET_AFTER_REQUEST";

export default {
  USERS_REQUEST,
  USERS_ERROR,
  USERS_SUCCESS,
  USER_ADD_REQUEST,
  USER_ADD_ERROR,
  USER_ADD_SUCCESS,
  USER_EDIT_REQUEST,
  USER_EDIT_ERROR,
  USER_EDIT_SUCCESS,
  USER_DELETE_REQUEST,
  USER_DELETE_ERROR,
  USER_DELETE_SUCCESS,
  RESET_AFTER_REQUEST,
};