const BROKERS_REQUEST = "BROKERS_REQUEST";
const BROKERS_ERROR = "BROKERS_ERROR";
const BROKERS_SUCCESS = "BROKERS_SUCCESS";
const BROKER_ADD_REQUEST = "BROKER_ADD_REQUEST";
const BROKER_ADD_ERROR = "BROKER_ADD_ERROR";
const BROKER_ADD_SUCCESS = "BROKER_ADD_SUCCESS";
const BROKER_EDIT_REQUEST = "BROKER_EDIT_REQUEST";
const BROKER_EDIT_ERROR = "BROKER_EDIT_ERROR";
const BROKER_EDIT_SUCCESS = "BROKER_EDIT_SUCCESS";
const BROKER_DELETE_REQUEST = "BROKER_DELETE_REQUEST";
const BROKER_DELETE_ERROR = "BROKER_DELETE_ERROR";
const BROKER_DELETE_SUCCESS = "BROKER_DELETE_SUCCESS";

const RESET_AFTER_REQUEST = "RESET_AFTER_REQUEST";

export default {
  BROKERS_REQUEST,
  BROKERS_ERROR,
  BROKERS_SUCCESS,
  BROKER_ADD_REQUEST,
  BROKER_ADD_ERROR,
  BROKER_ADD_SUCCESS,
  BROKER_EDIT_REQUEST,
  BROKER_EDIT_ERROR,
  BROKER_EDIT_SUCCESS,
  BROKER_DELETE_REQUEST,
  BROKER_DELETE_ERROR,
  BROKER_DELETE_SUCCESS,
  RESET_AFTER_REQUEST,
};