const SETTINGS_REQUEST = "SETTINGS_REQUEST";
const SETTINGS_ERROR = "SETTINGS_ERROR";
const SETTINGS_SUCCESS = "SETTINGS_SUCCESS";
const SETTING_ADD_REQUEST = "SETTING_ADD_REQUEST";
const SETTING_ADD_ERROR = "SETTING_ADD_ERROR";
const SETTING_ADD_SUCCESS = "SETTING_ADD_SUCCESS";
const SETTING_EDIT_REQUEST = "SETTING_EDIT_REQUEST";
const SETTING_EDIT_ERROR = "SETTING_EDIT_ERROR";
const SETTING_EDIT_SUCCESS = "SETTING_EDIT_SUCCESS";
const SETTING_DELETE_REQUEST = "SETTING_DELETE_REQUEST";
const SETTING_DELETE_ERROR = "SETTING_DELETE_ERROR";
const SETTING_DELETE_SUCCESS = "SETTING_DELETE_SUCCESS";

const RESET_AFTER_REQUEST = "RESET_AFTER_REQUEST";

export default {
  SETTINGS_REQUEST,
  SETTINGS_ERROR,
  SETTINGS_SUCCESS,
  SETTING_ADD_REQUEST,
  SETTING_ADD_ERROR,
  SETTING_ADD_SUCCESS,
  SETTING_EDIT_REQUEST,
  SETTING_EDIT_ERROR,
  SETTING_EDIT_SUCCESS,
  SETTING_DELETE_REQUEST,
  SETTING_DELETE_ERROR,
  SETTING_DELETE_SUCCESS,
  RESET_AFTER_REQUEST,
};