const ALL_USER_ACCOUNTS_REQUEST = "ALL_USER_ACCOUNTS_REQUEST";
const ALL_USER_ACCOUNTS_ERROR = "ALL_USER_ACCOUNTS_ERROR";
const ALL_USER_ACCOUNTS_SUCCESS = "ALL_USER_ACCOUNTS_SUCCESS";
const USER_ACCOUNTS_REQUEST = "USER_ACCOUNTS_REQUEST";
const USER_ACCOUNTS_ERROR = "USER_ACCOUNTS_ERROR";
const USER_ACCOUNTS_SUCCESS = "USER_ACCOUNTS_SUCCESS";
const USER_ACCOUNT_ADD_REQUEST = "USER_ACCOUNT_ADD_REQUEST";
const USER_ACCOUNT_ADD_ERROR = "USER_ACCOUNT_ADD_ERROR";
const USER_ACCOUNT_ADD_SUCCESS = "USER_ACCOUNT_ADD_SUCCESS";
const USER_ACCOUNT_EDIT_REQUEST = "USER_ACCOUNT_EDIT_REQUEST";
const USER_ACCOUNT_EDIT_ERROR = "USER_ACCOUNT_EDIT_ERROR";
const USER_ACCOUNT_EDIT_SUCCESS = "USER_ACCOUNT_EDIT_SUCCESS";
const USER_ACCOUNT_DELETE_REQUEST = "USER_ACCOUNT_DELETE_REQUEST";
const USER_ACCOUNT_DELETE_ERROR = "USER_ACCOUNT_DELETE_ERROR";
const USER_ACCOUNT_DELETE_SUCCESS = "USER_ACCOUNT_DELETE_SUCCESS";

const RESET_AFTER_REQUEST = "RESET_AFTER_REQUEST";

export default {
  ALL_USER_ACCOUNTS_REQUEST,
  ALL_USER_ACCOUNTS_ERROR,
  ALL_USER_ACCOUNTS_SUCCESS,
  USER_ACCOUNTS_REQUEST,
  USER_ACCOUNTS_ERROR,
  USER_ACCOUNTS_SUCCESS,
  USER_ACCOUNT_ADD_REQUEST,
  USER_ACCOUNT_ADD_ERROR,
  USER_ACCOUNT_ADD_SUCCESS,
  USER_ACCOUNT_EDIT_REQUEST,
  USER_ACCOUNT_EDIT_ERROR,
  USER_ACCOUNT_EDIT_SUCCESS,
  USER_ACCOUNT_DELETE_REQUEST,
  USER_ACCOUNT_DELETE_ERROR,
  USER_ACCOUNT_DELETE_SUCCESS,
  RESET_AFTER_REQUEST,
};