const PAGES_REQUEST = "PAGES_REQUEST";
const PAGES_ERROR = "PAGES_ERROR";
const PAGES_SUCCESS = "PAGES_SUCCESS";
const PAGE_REQUEST = "PAGE_REQUEST";
const PAGE_ERROR = "PAGE_ERROR";
const PAGE_SUCCESS = "PAGE_SUCCESS";
const PAGE_ADD_REQUEST = "PAGE_ADD_REQUEST";
const PAGE_ADD_ERROR = "PAGE_ADD_ERROR";
const PAGE_ADD_SUCCESS = "PAGE_ADD_SUCCESS";
const PAGE_EDIT_REQUEST = "PAGE_EDIT_REQUEST";
const PAGE_EDIT_ERROR = "PAGE_EDIT_ERROR";
const PAGE_EDIT_SUCCESS = "PAGE_EDIT_SUCCESS";
const PAGE_DELETE_REQUEST = "PAGE_DELETE_REQUEST";
const PAGE_DELETE_ERROR = "PAGE_DELETE_ERROR";
const PAGE_DELETE_SUCCESS = "PAGE_DELETE_SUCCESS";

const RESET_AFTER_REQUEST = "RESET_AFTER_REQUEST";

export default {
  PAGES_REQUEST,
  PAGES_ERROR,
  PAGES_SUCCESS,
  PAGE_REQUEST,
  PAGE_ERROR,
  PAGE_SUCCESS,
  PAGE_ADD_REQUEST,
  PAGE_ADD_ERROR,
  PAGE_ADD_SUCCESS,
  PAGE_EDIT_REQUEST,
  PAGE_EDIT_ERROR,
  PAGE_EDIT_SUCCESS,
  PAGE_DELETE_REQUEST,
  PAGE_DELETE_ERROR,
  PAGE_DELETE_SUCCESS,
  RESET_AFTER_REQUEST,
};