const MARKET_OPERATIONS_REQUEST = "MARKET_OPERATIONS_REQUEST";
const MARKET_OPERATIONS_ERROR = "MARKET_OPERATIONS_ERROR";
const MARKET_OPERATIONS_SUCCESS = "MARKET_OPERATIONS_SUCCESS";
const MARKET_OPERATION_ADD_REQUEST = "MARKET_OPERATION_ADD_REQUEST";
const MARKET_OPERATION_ADD_ERROR = "MARKET_OPERATION_ADD_ERROR";
const MARKET_OPERATION_ADD_SUCCESS = "MARKET_OPERATION_ADD_SUCCESS";
const MARKET_OPERATION_EDIT_REQUEST = "MARKET_OPERATION_EDIT_REQUEST";
const MARKET_OPERATION_EDIT_ERROR = "MARKET_OPERATION_EDIT_ERROR";
const MARKET_OPERATION_EDIT_SUCCESS = "MARKET_OPERATION_EDIT_SUCCESS";
const MARKET_OPERATION_DELETE_REQUEST = "MARKET_OPERATION_DELETE_REQUEST";
const MARKET_OPERATION_DELETE_ERROR = "MARKET_OPERATION_DELETE_ERROR";
const MARKET_OPERATION_DELETE_SUCCESS = "MARKET_OPERATION_DELETE_SUCCESS";

const RESET_AFTER_REQUEST = "RESET_AFTER_REQUEST";

export default {
  MARKET_OPERATIONS_REQUEST,
  MARKET_OPERATIONS_ERROR,
  MARKET_OPERATIONS_SUCCESS,
  MARKET_OPERATION_ADD_REQUEST,
  MARKET_OPERATION_ADD_ERROR,
  MARKET_OPERATION_ADD_SUCCESS,
  MARKET_OPERATION_EDIT_REQUEST,
  MARKET_OPERATION_EDIT_ERROR,
  MARKET_OPERATION_EDIT_SUCCESS,
  MARKET_OPERATION_DELETE_REQUEST,
  MARKET_OPERATION_DELETE_ERROR,
  MARKET_OPERATION_DELETE_SUCCESS,
  RESET_AFTER_REQUEST,
};