const ASSET_CLASSES_REQUEST = "ASSET_CLASSES_REQUEST";
const ASSET_CLASSES_ERROR = "ASSET_CLASSES_ERROR";
const ASSET_CLASSES_SUCCESS = "ASSET_CLASSES_SUCCESS";
const ASSET_CLASS_ADD_REQUEST = "ASSET_CLASS_ADD_REQUEST";
const ASSET_CLASS_ADD_ERROR = "ASSET_CLASS_ADD_ERROR";
const ASSET_CLASS_ADD_SUCCESS = "ASSET_CLASS_ADD_SUCCESS";
const ASSET_CLASS_EDIT_REQUEST = "ASSET_CLASS_EDIT_REQUEST";
const ASSET_CLASS_EDIT_ERROR = "ASSET_CLASS_EDIT_ERROR";
const ASSET_CLASS_EDIT_SUCCESS = "ASSET_CLASS_EDIT_SUCCESS";
const ASSET_CLASS_DELETE_REQUEST = "ASSET_CLASS_DELETE_REQUEST";
const ASSET_CLASS_DELETE_ERROR = "ASSET_CLASS_DELETE_ERROR";
const ASSET_CLASS_DELETE_SUCCESS = "ASSET_CLASS_DELETE_SUCCESS";

const RESET_AFTER_REQUEST = "RESET_AFTER_REQUEST";

export default {
  ASSET_CLASSES_REQUEST,
  ASSET_CLASSES_ERROR,
  ASSET_CLASSES_SUCCESS,
  ASSET_CLASS_ADD_REQUEST,
  ASSET_CLASS_ADD_ERROR,
  ASSET_CLASS_ADD_SUCCESS,
  ASSET_CLASS_EDIT_REQUEST,
  ASSET_CLASS_EDIT_ERROR,
  ASSET_CLASS_EDIT_SUCCESS,
  ASSET_CLASS_DELETE_REQUEST,
  ASSET_CLASS_DELETE_ERROR,
  ASSET_CLASS_DELETE_SUCCESS,
  RESET_AFTER_REQUEST,
};