const MARKET_MOVEMENTS_REQUEST = "MARKET_MOVEMENTS_REQUEST";
const MARKET_MOVEMENTS_ERROR = "MARKET_MOVEMENTS_ERROR";
const MARKET_MOVEMENTS_SUCCESS = "MARKET_MOVEMENTS_SUCCESS";
const MARKET_MOVEMENT_ADD_REQUEST = "MARKET_MOVEMENT_ADD_REQUEST";
const MARKET_MOVEMENT_ADD_ERROR = "MARKET_MOVEMENT_ADD_ERROR";
const MARKET_MOVEMENT_ADD_SUCCESS = "MARKET_MOVEMENT_ADD_SUCCESS";
const MARKET_MOVEMENT_EDIT_REQUEST = "MARKET_MOVEMENT_EDIT_REQUEST";
const MARKET_MOVEMENT_EDIT_ERROR = "MARKET_MOVEMENT_EDIT_ERROR";
const MARKET_MOVEMENT_EDIT_SUCCESS = "MARKET_MOVEMENT_EDIT_SUCCESS";
const MARKET_MOVEMENT_DELETE_REQUEST = "MARKET_MOVEMENT_DELETE_REQUEST";
const MARKET_MOVEMENT_DELETE_ERROR = "MARKET_MOVEMENT_DELETE_ERROR";
const MARKET_MOVEMENT_DELETE_SUCCESS = "MARKET_MOVEMENT_DELETE_SUCCESS";

const RESET_AFTER_REQUEST = "RESET_AFTER_REQUEST";

export default {
  MARKET_MOVEMENTS_REQUEST,
  MARKET_MOVEMENTS_ERROR,
  MARKET_MOVEMENTS_SUCCESS,
  MARKET_MOVEMENT_ADD_REQUEST,
  MARKET_MOVEMENT_ADD_ERROR,
  MARKET_MOVEMENT_ADD_SUCCESS,
  MARKET_MOVEMENT_EDIT_REQUEST,
  MARKET_MOVEMENT_EDIT_ERROR,
  MARKET_MOVEMENT_EDIT_SUCCESS,
  MARKET_MOVEMENT_DELETE_REQUEST,
  MARKET_MOVEMENT_DELETE_ERROR,
  MARKET_MOVEMENT_DELETE_SUCCESS,
  RESET_AFTER_REQUEST,
};