const FUND_MOVEMENTS_REQUEST = 'FUND_MOVEMENTS_REQUEST'
const FUND_MOVEMENTS_ERROR = 'FUND_MOVEMENTS_ERROR'
const FUND_MOVEMENTS_SUCCESS = 'FUND_MOVEMENTS_SUCCESS'
const FUND_MOVEMENT_ADD_REQUEST = 'FUND_MOVEMENT_ADD_REQUEST'
const FUND_MOVEMENT_ADD_ERROR = 'FUND_MOVEMENT_ADD_ERROR'
const FUND_MOVEMENT_ADD_SUCCESS = 'FUND_MOVEMENT_ADD_SUCCESS'
const FUND_MOVEMENT_EDIT_REQUEST = 'FUND_MOVEMENT_EDIT_REQUEST'
const FUND_MOVEMENT_EDIT_ERROR = 'FUND_MOVEMENT_EDIT_ERROR'
const FUND_MOVEMENT_EDIT_SUCCESS = 'FUND_MOVEMENT_EDIT_SUCCESS'
const FUND_MOVEMENT_DELETE_REQUEST = 'FUND_MOVEMENT_DELETE_REQUEST'
const FUND_MOVEMENT_DELETE_ERROR = 'FUND_MOVEMENT_DELETE_ERROR'
const FUND_MOVEMENT_DELETE_SUCCESS = 'FUND_MOVEMENT_DELETE_SUCCESS'

const RESET_AFTER_REQUEST = 'RESET_AFTER_REQUEST'

export default {
  FUND_MOVEMENTS_REQUEST,
  FUND_MOVEMENTS_ERROR,
  FUND_MOVEMENTS_SUCCESS,
  FUND_MOVEMENT_ADD_REQUEST,
  FUND_MOVEMENT_ADD_ERROR,
  FUND_MOVEMENT_ADD_SUCCESS,
  FUND_MOVEMENT_EDIT_REQUEST,
  FUND_MOVEMENT_EDIT_ERROR,
  FUND_MOVEMENT_EDIT_SUCCESS,
  FUND_MOVEMENT_DELETE_REQUEST,
  FUND_MOVEMENT_DELETE_ERROR,
  FUND_MOVEMENT_DELETE_SUCCESS,
  RESET_AFTER_REQUEST,
}
