const WIRE_TRANSFER_REQUESTS_REQUEST = "WIRE_TRANSFER_REQUESTS_REQUEST";
const WIRE_TRANSFER_REQUESTS_ERROR = "WIRE_TRANSFER_REQUESTS_ERROR";
const WIRE_TRANSFER_REQUESTS_SUCCESS = "WIRE_TRANSFER_REQUESTS_SUCCESS";
const WIRE_TRANSFER_REQUEST_REQUEST = "WIRE_TRANSFER_REQUEST_REQUEST";
const WIRE_TRANSFER_REQUEST_ERROR = "WIRE_TRANSFER_REQUEST_ERROR";
const WIRE_TRANSFER_REQUEST_SUCCESS = "WIRE_TRANSFER_REQUEST_SUCCESS";
const WIRE_TRANSFER_REQUEST_ADD_REQUEST = "WIRE_TRANSFER_REQUEST_ADD_REQUEST";
const WIRE_TRANSFER_REQUEST_ADD_ERROR = "WIRE_TRANSFER_REQUEST_ADD_ERROR";
const WIRE_TRANSFER_REQUEST_ADD_SUCCESS = "WIRE_TRANSFER_REQUEST_ADD_SUCCESS";
const WIRE_TRANSFER_REQUEST_EDIT_REQUEST = "WIRE_TRANSFER_REQUEST_EDIT_REQUEST";
const WIRE_TRANSFER_REQUEST_EDIT_ERROR = "WIRE_TRANSFER_REQUEST_EDIT_ERROR";
const WIRE_TRANSFER_REQUEST_EDIT_SUCCESS = "WIRE_TRANSFER_REQUEST_EDIT_SUCCESS";
const WIRE_TRANSFER_REQUEST_DELETE_REQUEST = "WIRE_TRANSFER_REQUEST_DELETE_REQUEST";
const WIRE_TRANSFER_REQUEST_DELETE_ERROR = "WIRE_TRANSFER_REQUEST_DELETE_ERROR";
const WIRE_TRANSFER_REQUEST_DELETE_SUCCESS = "WIRE_TRANSFER_REQUEST_DELETE_SUCCESS";

const WIRE_TRANSFER_REQUESTS_USER_ACCOUNT_REQUEST = "WIRE_TRANSFER_REQUESTS_USER_ACCOUNT_REQUEST";
const WIRE_TRANSFER_REQUESTS_USER_ACCOUNT_ERROR = "WIRE_TRANSFER_REQUESTS_USER_ACCOUNT_ERROR";
const WIRE_TRANSFER_REQUESTS_USER_ACCOUNT_SUCCESS = "WIRE_TRANSFER_REQUESTS_USER_ACCOUNT_SUCCESS";

const RESET_AFTER_REQUEST = "RESET_AFTER_REQUEST";

export default {
  WIRE_TRANSFER_REQUESTS_REQUEST,
  WIRE_TRANSFER_REQUESTS_ERROR,
  WIRE_TRANSFER_REQUESTS_SUCCESS,
  WIRE_TRANSFER_REQUEST_REQUEST,
  WIRE_TRANSFER_REQUEST_ERROR,
  WIRE_TRANSFER_REQUEST_SUCCESS,
  WIRE_TRANSFER_REQUEST_ADD_REQUEST,
  WIRE_TRANSFER_REQUEST_ADD_ERROR,
  WIRE_TRANSFER_REQUEST_ADD_SUCCESS,
  WIRE_TRANSFER_REQUEST_EDIT_REQUEST,
  WIRE_TRANSFER_REQUEST_EDIT_ERROR,
  WIRE_TRANSFER_REQUEST_EDIT_SUCCESS,
  WIRE_TRANSFER_REQUEST_DELETE_REQUEST,
  WIRE_TRANSFER_REQUEST_DELETE_ERROR,
  WIRE_TRANSFER_REQUEST_DELETE_SUCCESS,
  WIRE_TRANSFER_REQUESTS_USER_ACCOUNT_REQUEST,
  WIRE_TRANSFER_REQUESTS_USER_ACCOUNT_ERROR,
  WIRE_TRANSFER_REQUESTS_USER_ACCOUNT_SUCCESS,
  RESET_AFTER_REQUEST,

};