const USER_ACCOUNT_MOVEMENTS_REQUEST = "USER_ACCOUNT_MOVEMENTS_REQUEST";
const USER_ACCOUNT_MOVEMENTS_ERROR = "USER_ACCOUNT_MOVEMENTS_ERROR";
const USER_ACCOUNT_MOVEMENTS_SUCCESS = "USER_ACCOUNT_MOVEMENTS_SUCCESS";
const USER_ACCOUNT_MOVEMENT_ADD_REQUEST = "USER_ACCOUNT_MOVEMENT_ADD_REQUEST";
const USER_ACCOUNT_MOVEMENT_ADD_ERROR = "USER_ACCOUNT_MOVEMENT_ADD_ERROR";
const USER_ACCOUNT_MOVEMENT_ADD_SUCCESS = "USER_ACCOUNT_MOVEMENT_ADD_SUCCESS";
const USER_ACCOUNT_MOVEMENT_EDIT_REQUEST = "USER_ACCOUNT_MOVEMENT_EDIT_REQUEST";
const USER_ACCOUNT_MOVEMENT_EDIT_ERROR = "USER_ACCOUNT_MOVEMENT_EDIT_ERROR";
const USER_ACCOUNT_MOVEMENT_EDIT_SUCCESS = "USER_ACCOUNT_MOVEMENT_EDIT_SUCCESS";
const USER_ACCOUNT_MOVEMENT_DELETE_REQUEST = "USER_ACCOUNT_MOVEMENT_DELETE_REQUEST";
const USER_ACCOUNT_MOVEMENT_DELETE_ERROR = "USER_ACCOUNT_MOVEMENT_DELETE_ERROR";
const USER_ACCOUNT_MOVEMENT_DELETE_SUCCESS = "USER_ACCOUNT_MOVEMENT_DELETE_SUCCESS";

const RESET_AFTER_REQUEST = "RESET_AFTER_REQUEST";

export default {
  USER_ACCOUNT_MOVEMENTS_REQUEST,
  USER_ACCOUNT_MOVEMENTS_ERROR,
  USER_ACCOUNT_MOVEMENTS_SUCCESS,
  USER_ACCOUNT_MOVEMENT_ADD_REQUEST,
  USER_ACCOUNT_MOVEMENT_ADD_ERROR,
  USER_ACCOUNT_MOVEMENT_ADD_SUCCESS,
  USER_ACCOUNT_MOVEMENT_EDIT_REQUEST,
  USER_ACCOUNT_MOVEMENT_EDIT_ERROR,
  USER_ACCOUNT_MOVEMENT_EDIT_SUCCESS,
  USER_ACCOUNT_MOVEMENT_DELETE_REQUEST,
  USER_ACCOUNT_MOVEMENT_DELETE_ERROR,
  USER_ACCOUNT_MOVEMENT_DELETE_SUCCESS,
  RESET_AFTER_REQUEST,
};